theme: jekyll-theme-minimal
title: "Jason Chua"
description: "An aspiring computer science student trying to blend the latest in technology with traditional media."
linkedin_url: "https://www.linkedin.com/in/jchu04/"
