theme: jekyll-theme-minimal
title: "Jason Chua"
description: "A B.S. of Computer Science graduate and M.S. of Journalism student trying to blend the latest in technology with traditional media."
linkedin_url: "https://www.linkedin.com/in/jchu04/"
