theme: jekyll-theme-minimal
title: "Jason Chua"
description: "A computer Science graduate and Journalism student looking to push what's possible in the modern newsroom."
linkedin_url: "https://www.linkedin.com/in/jchu04/"
